# Generated by Django 4.1.2 on 2022-10-31 21:30

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('data', djongo.models.fields.JSONField(default={})),
                ('entity', models.TextField(default='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('acao', models.TextField()),
                ('tipo', models.TextField()),
                ('field', models.TextField()),
                ('entity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_name', models.TextField()),
                ('tipo', models.TextField(default='')),
                ('descricao', models.TextField()),
                ('acao_anterior', models.TextField()),
                ('acao_principal', models.TextField()),
                ('respostas', models.ManyToManyField(to='chatbot_cadastro_api.resposta')),
            ],
        ),
    ]
